### ISSUE TITLE
Change the confirm modal to delete a space

### ISSUE THREAD

**Issue by zak39** [arawa/workspace#369]
The confirm window currently is just a call from window API :

```javascript
const res = window.confirm(t('workspace', 'Are you sure you want to delete the {space} space ?', { space }))
```

![image](https://user-images.githubusercontent.com/28636549/140289466-eb8260d0-1093-4bc0-bfde-71ce008726eb.png)

I propose to change this window by a modal window with this component : https://www.npmjs.com/package/vue-confirm-dialog

Or with this Nextcloud's component : https://nextcloud-vue-components.netlify.app/#/Components/Modal

**Comment by LivOriona** [comment]
Fonctionnalité qui n'a plus lieu d'être : actuellement lorsqu'un workspace est supprimé, tous ses groupes liés sont supprimés automatiquement (GE-id, U-id, groupes fait main).
Par contre je suis favorable à adopter le visuel de ce composant : https://www.npmjs.com/package/vue-confirm-dialog  @zak39

**Comment by dorianne-arawa** [comment]
@zak39 i think it's done and we can close this issue?

**Comment by zak39** [comment]
Yes, we can close this issue now

**Comment by zak39** [comment]
The PR https://github.com/arawa/workspace/pull/774 anwsers this issue
