### ISSUE TITLE
Edit a space title putting cursor on it

### ISSUE THREAD

**Issue by zak39** [arawa/workspace#371]
To edit a space title, we have to follow this path : Click on a space detail > click on the meatballs menu to left > click on rename space .

I propose to change this way of doing things.

It's very interesting to edit the space title putting cursor on it from space detail.

![image](https://user-images.githubusercontent.com/28636549/140293993-1cbdaa21-0aa1-4d4b-b71c-9eeabcb99190.png)

We can use this component :  https://www.npmjs.com/package/vue-contenteditable or this : https://vuejsexamples.com/a-vue-component-wrapper-for-contenteditable/

**Comment by dorianne-arawa** [comment]
Corrected since the 3.0.2 app version. I close this issue.
