### ISSUE TITLE
Modify error message : two workspaces can't have the same name

### ISSUE THREAD

**Issue by LivOriona** [arawa/workspace#421]
- When a user tries to create a Workspace with a name similar to another already existing Workspace, the error message is displayed.

- [x] This error message should be modified as follows:

> **Error - This workspace name already exists** 
> Please enter a new workspace name. Please note that workspace names are not case sensitive (france and FRANCE are considered the same workspace name)

- [x] Do the same for the French version of the application:

> **Erreur - Ce nom d'espace de travail existe déjà** 
> Veuillez saisir un nouveau nom d'espace de travail. Attention, les noms d'espaces de travail ne sont pas sensibles à la casse (france et FRANCE sont considérés comme un même nom d'espace de travail)

- [x] Increase the duration of the error message if possible

**Comment by zak39** [comment]
@LivOriona I created the PR #423 

Don't worry about create space button which is bottom. I am creating a fix

**Comment by LivOriona** [comment]
Validated in my comment on the #423 PR
