### ISSUE TITLE
Change display name of Workspaces in notifications

### ISSUE THREAD

**Issue by LivOriona** [arawa/workspace#443]
I would like to see, in all notifications (email and push) about Workspace and Groups of users, the name of a Workspace and the name of the groups clearly displayed, instead of seeing the ID of a Workspace.
Examples:
- "Dorianne added you to the group GE of MyWorkspace" instead of "Dorianne added you to the group GE-7"
- "Dorianne added you to the group read-only of MyWorkspace" instead of "Dorianne added you to the group read-only-7"

This means to change the name of a group, which need to be discussed, in terms of feasibility and impact on other features. Or, is this possible to impact only the display of the groupname into the Nextcloud and email notifications?

**Comment by LivOriona** [comment]
linked to #467

**Comment by dorianne-arawa** [comment]
With the new app version 3.0.2 it should have been done, for WM-WorkspaceName and U-WorkspaceName. So I close this issue.
