### ISSUE TITLE
Modify GE-ID and U-ID group names

### ISSUE THREAD

**Issue by LivOriona** [arawa/workspace#467]
Proposition à étudier afin de modifier au moins l'affichage du nom de ces groupes dans l'application Workspace. Voir les impacts sur les notifications, et dans nextcloud files (autorisation avancées), et dans l'interface de gestion des utilisateurs.
@Jerome-Herbinet

**Comment by LivOriona** [comment]
linked to #443

**Comment by dorianne-arawa** [comment]
With the new app version 3.0.2 it should have been done, for WM-WorkspaceName and U-WorkspaceName. So I close this issue.
