### ISSUE TITLE
Error 500 on creating a workspace

### ISSUE THREAD

**Issue by small1** [arawa/workspace#608]
I have been testing out this app on my demo environments. We are using apache and php 8.0 and i get an error 500 when i try to create a workspace.   A groupfolder is created in the groupfolder app ( I am using the forked one ). But no workspace is in the list afterwards.

Error i get in the logfile is:
`
{"reqId":"nAKFwVbIzBslJCgGfK4t","level":3,"time":"2022-11-03T09:48:56+00:00","remoteAddr":"2.69.179.28","user":"admin","app":"index","method":"POST","url":"/apps/workspace/spaces","message":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher::afterException(): Return value must be of type OCP\\AppFramework\\Http\\Response, null returned","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.18","exception":{"Exception":"TypeError","Message":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher::afterException(): Return value must be of type OCP\\AppFramework\\Http\\Response, null returned","Code":0,"Trace":[{"file":"/var/www/nextcloud/uka/lib/private/AppFramework/Http/Dispatcher.php","line":163,"function":"afterException","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/var/www/nextcloud/uka/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/uka/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/uka/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/uka/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/uka/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","Line":121,"CustomMessage":"--"}}
`

**Comment by gaudryc** [comment]
I have the same issue here.
After some research, i found that the issue is located in apps/workspace/lib/Db/SpaceMapper.php, in the checkSpaceNameExist method. The SQL request is wrong because, the WHERE condition uses some double quotes around the string value instead of escaped single quote.

It should be patch immediately because it does not work from a long time. It demonstrates that this application has not been tested at all for a long time also.
It should be patch immediately because it is a security breach (this query should use named parameter).

**Comment by sergeng** [comment]
https://github.com/arawa/workspace/compare/main...sergeng:workspace:patch-1

**Comment by Aguay-val** [comment]
This is working well :tada:

**Comment by zak39** [comment]
Hi :)

I'm sorry to answer you late.
I am creating an PR to fix this issue.
