### ISSUE TITLE
Converting groupfolders to workspaces

### ISSUE THREAD

**Issue by zak39** [arawa/workspace#629]
- [x] Convert one or more groupfolders in workspaces.
- [x] When the converting, we checkbox the advanced permissions.
- [x] When the converting, if there are groups in the advanced permissions, we will import them in the `GE-<ID>`.
    - [x] Then, we remove these groups from Advanced Permissions.
- [x] change the name of the "Import / Convert" feature to "Convert"
    - [x] make the change in the French version of the application as well, from "Importer / Convertir" to "Convertir"

Hey @dorianne-arawa :wave:

**Comment by dorianne-arawa** [comment]
@zak39 i updated your comment to add the actions I had in mind.

**Comment by zak39** [comment]
> @zak39 i updated your comment to add the actions I had in mind.

@dorianne-arawa I checked all check-box ! All tasks are already completed :wink:
