### ISSUE TITLE
Convert group folder into a workspace : rename a group doesn't work

### ISSUE THREAD

**Issue by dorianne-arawa** [arawa/workspace#639]
After converting a group folder, which contained at least one local group of users, into a Workspace, rename this users group doesn't work. To reproduce the bug, follow these instructions: 
- convert a group folder, with at least 1 local group
- rename this local converted group :
  - in the left side panel, the renamed group name as disapeared
  - in this users group management interface, the renamed group name has disapear
- reload the page :
  - the group name never changed, neither in the left side panel, nor in the group management interface

The desired behavior, after converting a group folder that contained at least one local group of users, is as follows:
- when renaming the previously converted local group, the left side panel should show the new group name with a suffix "<chosen name>-ID"
- in this local group manangement interface, the group name should appear as "<chosen name>-ID"
- after reloading the page, the changes must be conserved

![10 local group name right after conversion](https://user-images.githubusercontent.com/105436767/209346488-b41ac393-8161-48ce-a956-09165478a0e4.png)
- this is the local group name after conversion "Team SysAdmin"

![11 renaming the group into sysAd team](https://user-images.githubusercontent.com/105436767/209346560-ebc3b305-e5b0-4567-829f-d674a425e88f.png)
- trying to rename local converted group "Team SysAdmin" into "adSys team"

![12 no more group name after renaming](https://user-images.githubusercontent.com/105436767/209346689-05a62f76-2796-46ee-898c-daf9f8fdb9c5.png)
- the new group name has disapeared

![13 result after a reload the group was not renamed](https://user-images.githubusercontent.com/105436767/209346726-1654f095-8ec2-40d3-8f56-0772fd784e40.png)
- after reloading the page, nothing changed

**Comment by zak39** [comment]
I fixed this bug here https://github.com/arawa/workspace/pull/633
