### ISSUE TITLE
occ commands?

### ISSUE THREAD

**Issue by donquixote** [arawa/workspace#674]
The groupfolders app has occ commands:

```
      groupfolders:create
      groupfolders:delete
      groupfolders:expire
      groupfolders:group
      groupfolders:list 
      groupfolders:permissions
      groupfolders:quota
      groupfolders:rename
      groupfolders:scan
      groupfolders:trashbin:cleanup
```

Are you planning to add commands for workspace?

**Comment by dorianne-arawa** [comment]
Hi @donquixote, 

We do not have any plans to make any `occ` orders for Workspace yet. It could be an ordered development in the future, but it is not yet the case at this time.
