### ISSUE TITLE
Comparison groupfolders vs workspace

### ISSUE THREAD

**Issue by donquixote** [arawa/workspace#675]
Hello,
I think it would be useful to have a comparison of plain groupfolders vs workspaces, in the README or elsewhere.

What I understand so far:
- Workspace has a dedicated and easily accessible page to manage workspaces, whereas groupfolders admin page is hidden in the admin settings.
- Each workspace starts with dedicated groups U-n and GE-n, whereas groupfolders start with no groups, and need to have them manually created.
- A workspace can have a color code
- A workspace has a name that can be distinct from the group folder name:
  - Changing the workspace name also changes the group folder name.
  - Changing the group folder name does _not_ change the workspace name.
  - The "Files" tab shows the group folder name, not the workspace name (if they are different).
  - The "Workspaces" tab shows the workspace name, not the group folder name (if they are different). But this seems to be the only place.
- A workspace has its own auto-increment id, that can be different from the group id.

**Comment by dorianne-arawa** [comment]
Hi @donquixote,

Thank you for your comment. Indeed, we could consider adding a comparison of Group folders (alone) and Workspace (based on Group folders, which is still needed). We will take this suggestion into account and see if we can add such information. 

Here is my quick answer to your various questions:

- **Workspace has a dedicated and easily accessible page to manage workspaces, whereas groupfolders admin page is hidden in the admin settings.**
    - Yes. I add that from Workspace 2.0.0 (when this version will be released, for nextcloud 25), General Managers (GM) will be able to see the `Group folders` section in their `settings`, in the `Administration `section. The Workspace Managers (WM) will also be able to manage the workspaces (with less rights than the GM) but will not see the `Group folders` section in their `settings`.


- **Each workspace starts with dedicated groups U-n and GE-n, whereas groupfolders start with no groups, and need to have them manually created.**
    - yes. And if a Workspace is created, you will see these groups (`U-n` and `GE-n`) in the `Group folders settings`.

- **A workspace can have a color code**
    - yes. It is visible only inside Workspace, not in Nextcloud Files app.

- **Changing the workspace name also changes the group folder name.**
    - yes

- **Changing the group folder name does not change the workspace name.**
    - yes, once workspace is installed and configured, there is no need to do anything in the `group folders settings`.

- **The "Files" tab shows the group folder name, not the workspace name (if they are different).**
    - yes

- **The "Workspaces" tab shows the workspace name, not the group folder name (if they are different). But this seems to be the only place.**
    - yes

- **A workspace has its own auto-increment id, that can be different from the group id.**
    - yes,

**Comment by zak39** [comment]
If it's okay with both of you, I close this issue
