### ISSUE TITLE
Exception classes namespace does not match PSR-4 directory structure

### ISSUE THREAD

**Issue by donquixote** [arawa/workspace#701]
After fixing a few other problems, I found this in the log:

> [..]
> Caused by Error: Class "OCA\Workspace\WorkspaceNameExistException" not found
/var/www/html/custom_apps/workspace/lib/Controller/WorkspaceController.php - line 109:

The reason is that exception classes are in `OCA\Workspace`, when according to the directory structure they should be in `OCA\Workspace\Exceptions`.

Btw, I found that in nextcloud core, these namespaces are named `\Exception\`, not `\Exceptions\`.
However, in apps, I found is an equal number of both.
In the general PHP world it seems singular `\Exception\` is more common.

**Comment by zak39** [comment]
Thank you, @donquixote, for your feedback !

We had already fixed this problem : https://github.com/arawa/workspace/tree/main/lib/Exceptions .

I close this issue.
