### ISSUE TITLE
Nextcloud 26 compatibility

### ISSUE THREAD

**Issue by Tealk** [arawa/workspace#788]
Hello,

Has anyone tried the app on v26? Are there any expected problems or can I use it without hesitation?

**Comment by kikislater** [comment]
No answer yet ?

**Comment by Tealk** [comment]
No longer needed with v27

**Comment by kikislater** [comment]
You mean that workspace ils available in v27?

**Comment by Tealk** [comment]
A little different, from v27 can be added circles to groupfolders, I have already tried and works wonderfully.

**Comment by delacosta456** [comment]
@Tealk thanks for this information
Will be possible to have comparison of similarity/differences between Workspace and the Circle app in NC7, for more understanding?
Thanks

**Comment by Tealk** [comment]
I would not like to make a statement, I have never actively used workspace.

**Comment by delacosta456** [comment]
@Tealk Workspace is completely different in it's logic/presentation and can be considered as a more advanced system.
@kikislater they release the 3.0.2 version compatible with 26  .. Let us try it

**Comment by zak39** [comment]
I think @dorianne-arawa answered your questions.

I close this issue.
