### ISSUE TITLE
Question: Will the workspace app be compatible with Nextcloud 28?

### ISSUE THREAD

**Issue by dancesWithCycles** [arawa/workspace#917]
Hi folks,
Thank you so much for providing and maintaining this repository. I like this app very much. That is why I am wondering if a version compatible with Nextcloud 28 will be available.

My Nextcloud instance is saying this.

```
A new version is available: Nextcloud 28.0.2
2 apps have no compatible version for this Nextcloud version available.
Apps missing compatible version

...
    [Workspace ↗](https://apps.nextcloud.com/apps/workspace)
```

That is why I am reluctant to update my Nextcloud instance. I do not want to lose this app.

How would you proceed?

Cheers!

**Comment by zak39** [comment]
Hi @dancesWithCycles :slightly_smiling_face: 

Thank you for your interest in our application :heart: 

We are releasing a new version for Nextcloud 28 next week.

We are sorry for the delay, and we hope the Workspace app continues to meet your expectations :+1:
